#!/bin/bash

board_to_cpu=`sed -e 's/#.*//' -e '/^$/d' <<EOF
# AMCC Eval boards
acadia		PPC405EZ
bamboo		PPC440EP
bubinga		PPC405EP
ebony		PPC440GP
katmai		PPC440SPe
katmai2		PPC440SPe
luan		PPC440SP
ocotea		PPC440GX
rainier		PPC440GRx
sequoia		PPC440EPx
sycamore	PPC405GPr
taihu		PPC405EP
taishan		PPC440GX
walnut		PPC405GP
whirlwind	PPC440SPe
yellowstone	PPC440GR
yosemite	PPC440EP
yucca		PPC440SPe
yucca_a		PPC440SPe

# Freescale
lite5200b	MPC5200
mpc5121		MPC5121e

# MicroSys
pm520		MPC5200
pm854		MPC8540

# PA-Semi
electra		PA6T-1682M

# TQ-Systems
tqm8xxl		MPC823
tqm860		MPC860
tqm885d		MPC885
tqm5200		MPC5200
tqm8540		MPC8540
tqm8560		MPC8560
EOF`

cpu_to_eldkcc=`sed -e 's/#.*//' -e '/^$/d' <<EOF
# AMCC
PPC405EP	ppc_4xx
PPC405EZ	ppc_4xx
PPC405GPr	ppc_4xx
PPC440EP	ppc_4xxFP
PPC440EPx	ppc_4xxFP
PPC440GP	ppc_4xx
PPC440GR	ppc_4xx
PPC440GRx	ppc_4xx
PPC440GX	ppc_4xx
PPC440SP	ppc_4xx
PPC440SPe	ppc_4xx

# Atmel
AT91RM9200	arm

# Freescale
MPC823		ppc_8xx
MPC860		ppc_8xx
MPC885		ppc_8xx
MPC5200		ppc_6xx
MPC5121e        ppc_83xx
MPC8540		ppc_85xx
MPC8560		ppc_85xx

# Infineon
INCAIP		mips_4KCle

# PA-Semi
PA6T-1682M	pa6t
EOF`

function usage {
    echo "usage: `basename $0` <from> <to> <key>"				1>&2
    echo "	The table { <from>, <to> } is queried for <from> = <key>"	1>&2
    echo "	where <from> and <to> are fieldnames."				1>&2
    echo "       `basename $0` <column>"					1>&2
    echo "	Lists all possible values for <column> where"			1>&2
    echo "	<column> is a fieldname."					1>&2
    echo "	Valid field names: 'board', 'cpu', 'eldkcc'"			1>&2
    echo "	(can be abbreviated as 'b', 'c', 'e')"				1>&2
    echo ""									1>&2
    echo "	Examples:"							1>&2
    echo "	eldk-map c b ppc440epx  - show all boards using 440EPx"		1>&2
    echo "	eldk-map e b ppc_8xx    - show all boards using ppc_8xx-"	1>&2
    echo "	  as CROSS_COMPILE."						1>&2
    echo "	eldk-map c              - show all known CPUs"			1>&2
    exit 1
}

function toupper {
    echo $1 | tr 'a-z' 'A-Z'
}

function tolower {
    echo $1 | tr 'A-Z' 'a-z'
}

# Map a board to its cpu
function board_to_cpu {
    while read board cpu
    do
	if [ "$1" = "`toupper $board`" ]
	then
	    echo $cpu
	    break
	fi
    done <<<"$board_to_cpu"
}

# Map a cpu to all boards using it
function cpu_to_board {
    while read board cpu
    do
	if [ "$1" = "`toupper $cpu`" ]
	then
	    echo $board
	fi
    done <<<"$board_to_cpu"
}

# Enumerate a column over the whole table
function enum_board_cpu {
    while read board cpu
    do
	eval "echo \$$1"
    done <<<"$board_to_cpu"
}

# Map a CPU to its ELDK architecture
function cpu_to_eldkcc {
    while read cpu eldkcc
    do
	if [ "$1" = "`toupper $cpu`" ]
	then
	    echo $eldkcc
	    break
	fi
    done <<<"$cpu_to_eldkcc"
}

# Map a CPU to its ELDK architecture
function eldkcc_to_cpu {
    while read cpu eldkcc
    do
	if [ "$1" = "`toupper $eldkcc`" ]
	then
	    echo $cpu
	fi
    done <<<"$cpu_to_eldkcc"
}

# Enumerate a column over the whole table
function enum_cpu_eldkcc {
    while read cpu eldkcc
    do
	eval "echo \$$1"
    done <<<"$cpu_to_eldkcc"
}

if [ $# -eq 1 ]
then
    # Lookup all values
    column=$(tolower $1)
    case ${column:0:1} in
	b)      enum_board_cpu board | sort | uniq ;;
	c)	enum_cpu_eldkcc cpu | sort | uniq ;;
	e)      enum_cpu_eldkcc eldkcc | sort | uniq ;;
	*)	echo "$0: unknown column $1" 1>&2 ; exit 1 ;;
    esac
elif [ $# -eq 3 ]
then
    # Map a $key through a table
    from=$(tolower $1)
    to=$(tolower $2)
    key=$(toupper $3)

    case "${from:0:1},${to:0:1}" in
	b,c)	board_to_cpu $key ;;
	c,e)	cpu_to_eldkcc $key ;;
	c,b)	cpu_to_board $key ;;
	e,c)	eldkcc_to_cpu $key ;;
	e,b)
	for cpu in `eldkcc_to_cpu $key` ; do
	    cpu_to_board $(toupper $cpu)
	done ;;
	*)  echo "$0: unknown lookup operation $from -> $to" 1>&2
	    exit 1 ;;
    esac
else
    usage
fi
